Table users {
    id int [pk, increment]
    firstname varchar(255) [not null]
    lastname varchar(255) [not null]
    email varchar(255) [not null, unique]
    password varchar(255) [not null, unique]
    age int
}